services:
  rabbitmq:
    build: .
    container_name: rabbitmq
    ports:
      - "5672:5672"     # Port AMQP
      - "15672:15672"   # Interface Web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  init-rabbitmq: 
    image: alpine:latest
    depends_on:
      - rabbitmq
    volumes:
      - ./init.sh:/init.sh
    entrypoint: [ "sh", "-c", "apk add --no-cache bash curl jq && chmod +x /init.sh && /init.sh" ]

volumes:
  rabbitmq_data:
